"""Add separation models

Revision ID: 377972f59377
Revises: 
Create Date: 2025-12-22 17:20:20.294903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377972f59377'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=True),
    sa.Column('half_day_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('full_day_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('overtime_start_after_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('max_overtime_hours_per_day', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('max_break_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('auto_deduct_break', sa.Boolean(), nullable=True),
    sa.Column('allow_multiple_punches', sa.Boolean(), nullable=True),
    sa.Column('require_punch_out', sa.Boolean(), nullable=True),
    sa.Column('auto_punch_out_after_hours', sa.Integer(), nullable=True),
    sa.Column('restrict_punch_location', sa.Boolean(), nullable=True),
    sa.Column('allowed_ip_addresses', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_policies_id'), 'attendance_policies', ['id'], unique=False)
    op.create_table('bulk_onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('operation_name', sa.String(length=255), nullable=False),
    sa.Column('total_candidates', sa.Integer(), nullable=True),
    sa.Column('successful_sends', sa.Integer(), nullable=True),
    sa.Column('failed_sends', sa.Integer(), nullable=True),
    sa.Column('verify_mobile', sa.Boolean(), nullable=True),
    sa.Column('verify_pan', sa.Boolean(), nullable=True),
    sa.Column('verify_bank', sa.Boolean(), nullable=True),
    sa.Column('verify_aadhaar', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('results_summary', sa.Text(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_onboarding_id'), 'bulk_onboarding', ['id'], unique=False)
    op.create_table('offer_letter_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('available_variables', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_letter_templates_id'), 'offer_letter_templates', ['id'], unique=False)
    op.create_table('onboarding_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('form_expiry_days', sa.Integer(), nullable=True),
    sa.Column('allow_form_editing', sa.Boolean(), nullable=True),
    sa.Column('require_document_upload', sa.Boolean(), nullable=True),
    sa.Column('send_welcome_email', sa.Boolean(), nullable=True),
    sa.Column('send_reminder_emails', sa.Boolean(), nullable=True),
    sa.Column('reminder_frequency_days', sa.Integer(), nullable=True),
    sa.Column('default_verify_mobile', sa.Boolean(), nullable=True),
    sa.Column('default_verify_pan', sa.Boolean(), nullable=True),
    sa.Column('default_verify_bank', sa.Boolean(), nullable=True),
    sa.Column('default_verify_aadhaar', sa.Boolean(), nullable=True),
    sa.Column('enable_auto_approval', sa.Boolean(), nullable=True),
    sa.Column('auto_approval_criteria', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.Text(), nullable=True),
    sa.Column('welcome_email_template', sa.Text(), nullable=True),
    sa.Column('reminder_email_template', sa.Text(), nullable=True),
    sa.Column('approval_email_template', sa.Text(), nullable=True),
    sa.Column('rejection_email_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_settings_id'), 'onboarding_settings', ['id'], unique=False)
    op.create_table('separation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('default_notice_period_days', sa.Integer(), nullable=True),
    sa.Column('allow_notice_period_buyout', sa.Boolean(), nullable=True),
    sa.Column('require_manager_approval', sa.Boolean(), nullable=True),
    sa.Column('require_hr_approval', sa.Boolean(), nullable=True),
    sa.Column('require_admin_approval', sa.Boolean(), nullable=True),
    sa.Column('mandatory_exit_interview', sa.Boolean(), nullable=True),
    sa.Column('exit_interview_template', sa.Text(), nullable=True),
    sa.Column('default_clearance_items', sa.Text(), nullable=True),
    sa.Column('auto_create_clearance', sa.Boolean(), nullable=True),
    sa.Column('notify_manager', sa.Boolean(), nullable=True),
    sa.Column('notify_hr', sa.Boolean(), nullable=True),
    sa.Column('notify_admin', sa.Boolean(), nullable=True),
    sa.Column('separation_request_template', sa.Text(), nullable=True),
    sa.Column('approval_notification_template', sa.Text(), nullable=True),
    sa.Column('rejection_notification_template', sa.Text(), nullable=True),
    sa.Column('clearance_reminder_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_separation_settings_id'), 'separation_settings', ['id'], unique=False)
    op.create_table('separation_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('available_variables', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_separation_templates_id'), 'separation_templates', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', name='maritalstatus'), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('religion', sa.String(length=100), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('date_of_confirmation', sa.Date(), nullable=True),
    sa.Column('date_of_termination', sa.Date(), nullable=True),
    sa.Column('employee_status', sa.Enum('ACTIVE', 'INACTIVE', 'TERMINATED', 'ON_LEAVE', 'PROBATION', name='employeestatus'), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('designation_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('reporting_manager_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('punch_in_time', sa.DateTime(), nullable=True),
    sa.Column('punch_out_time', sa.DateTime(), nullable=True),
    sa.Column('total_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('break_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('attendance_status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'LATE', 'ON_LEAVE', 'HOLIDAY', 'WEEKEND', name='attendancestatus'), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('is_early_out', sa.Boolean(), nullable=True),
    sa.Column('is_overtime', sa.Boolean(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('expected_in_time', sa.Time(), nullable=True),
    sa.Column('expected_out_time', sa.Time(), nullable=True),
    sa.Column('punch_in_location', sa.String(length=255), nullable=True),
    sa.Column('punch_out_location', sa.String(length=255), nullable=True),
    sa.Column('punch_in_ip', sa.String(length=45), nullable=True),
    sa.Column('punch_out_ip', sa.String(length=45), nullable=True),
    sa.Column('is_manual_entry', sa.Boolean(), nullable=True),
    sa.Column('manual_entry_reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['work_shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_attendance_date'), 'attendance_records', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_table('attendance_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_working_days', sa.Integer(), nullable=True),
    sa.Column('present_days', sa.Integer(), nullable=True),
    sa.Column('absent_days', sa.Integer(), nullable=True),
    sa.Column('half_days', sa.Integer(), nullable=True),
    sa.Column('late_days', sa.Integer(), nullable=True),
    sa.Column('leave_days', sa.Integer(), nullable=True),
    sa.Column('holiday_days', sa.Integer(), nullable=True),
    sa.Column('weekend_days', sa.Integer(), nullable=True),
    sa.Column('total_hours_worked', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('regular_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('break_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('attendance_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('punctuality_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_summaries_id'), 'attendance_summaries', ['id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_documents_id'), 'employee_documents', ['id'], unique=False)
    op.create_table('employee_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('present_address_line1', sa.String(length=255), nullable=True),
    sa.Column('present_address_line2', sa.String(length=255), nullable=True),
    sa.Column('present_city', sa.String(length=100), nullable=True),
    sa.Column('present_state', sa.String(length=100), nullable=True),
    sa.Column('present_country', sa.String(length=100), nullable=True),
    sa.Column('present_pincode', sa.String(length=20), nullable=True),
    sa.Column('permanent_address_line1', sa.String(length=255), nullable=True),
    sa.Column('permanent_address_line2', sa.String(length=255), nullable=True),
    sa.Column('permanent_city', sa.String(length=100), nullable=True),
    sa.Column('permanent_state', sa.String(length=100), nullable=True),
    sa.Column('permanent_country', sa.String(length=100), nullable=True),
    sa.Column('permanent_pincode', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('uan_number', sa.String(length=20), nullable=True),
    sa.Column('esi_number', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('bank_branch', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_mobile', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_address', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_number'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('pan_number')
    )
    op.create_index(op.f('ix_employee_profiles_id'), 'employee_profiles', ['id'], unique=False)
    op.create_table('employee_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('salary_structure_id', sa.Integer(), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ctc', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_salaries_id'), 'employee_salaries', ['id'], unique=False)
    op.create_table('onboarding_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('candidate_email', sa.String(length=255), nullable=False),
    sa.Column('candidate_mobile', sa.String(length=20), nullable=False),
    sa.Column('form_token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'EXPIRED', name='onboardingstatus'), nullable=True),
    sa.Column('verify_mobile', sa.Boolean(), nullable=True),
    sa.Column('verify_pan', sa.Boolean(), nullable=True),
    sa.Column('verify_bank', sa.Boolean(), nullable=True),
    sa.Column('verify_aadhaar', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_forms_candidate_email'), 'onboarding_forms', ['candidate_email'], unique=False)
    op.create_index(op.f('ix_onboarding_forms_form_token'), 'onboarding_forms', ['form_token'], unique=True)
    op.create_index(op.f('ix_onboarding_forms_id'), 'onboarding_forms', ['id'], unique=False)
    op.create_table('separation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('separation_type', sa.Enum('RESIGNATION', 'TERMINATION', 'RETIREMENT', 'END_OF_CONTRACT', 'LAYOFF', 'MUTUAL_SEPARATION', name='separationtype'), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='separationstatus'), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('last_working_date', sa.Date(), nullable=False),
    sa.Column('actual_separation_date', sa.Date(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('detailed_reason', sa.Text(), nullable=True),
    sa.Column('initiated_by', sa.String(length=50), nullable=True),
    sa.Column('final_settlement_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pending_dues', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('recovery_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('initiated_by_user', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('hr_notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_separation_requests_id'), 'separation_requests', ['id'], unique=False)
    op.create_table('shift_rosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('roster_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('custom_start_time', sa.Time(), nullable=True),
    sa.Column('custom_end_time', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['work_shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_rosters_id'), 'shift_rosters', ['id'], unique=False)
    op.create_index(op.f('ix_shift_rosters_roster_date'), 'shift_rosters', ['roster_date'], unique=False)
    op.create_table('attendance_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_record_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('correction_type', sa.String(length=50), nullable=False),
    sa.Column('original_punch_in', sa.DateTime(), nullable=True),
    sa.Column('original_punch_out', sa.DateTime(), nullable=True),
    sa.Column('corrected_punch_in', sa.DateTime(), nullable=True),
    sa.Column('corrected_punch_out', sa.DateTime(), nullable=True),
    sa.Column('leave_type_id', sa.Integer(), nullable=True),
    sa.Column('is_half_day', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('supporting_documents', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_corrections_id'), 'attendance_corrections', ['id'], unique=False)
    op.create_table('attendance_punches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_record_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('punch_time', sa.DateTime(), nullable=False),
    sa.Column('punch_type', sa.Enum('IN', 'OUT', 'BREAK_OUT', 'BREAK_IN', name='punchtype'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('is_biometric', sa.Boolean(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('manual_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_punches_id'), 'attendance_punches', ['id'], unique=False)
    op.create_table('exit_interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('separation_id', sa.Integer(), nullable=False),
    sa.Column('interview_date', sa.Date(), nullable=True),
    sa.Column('interviewer_id', sa.Integer(), nullable=True),
    sa.Column('interview_mode', sa.String(length=50), nullable=True),
    sa.Column('reason_for_leaving', sa.Text(), nullable=True),
    sa.Column('job_satisfaction_rating', sa.Integer(), nullable=True),
    sa.Column('manager_feedback', sa.Text(), nullable=True),
    sa.Column('company_culture_feedback', sa.Text(), nullable=True),
    sa.Column('work_environment_feedback', sa.Text(), nullable=True),
    sa.Column('growth_opportunities_feedback', sa.Text(), nullable=True),
    sa.Column('compensation_feedback', sa.Text(), nullable=True),
    sa.Column('would_recommend_company', sa.Boolean(), nullable=True),
    sa.Column('would_consider_rejoining', sa.Boolean(), nullable=True),
    sa.Column('suggestions_for_improvement', sa.Text(), nullable=True),
    sa.Column('positive_aspects', sa.Text(), nullable=True),
    sa.Column('negative_aspects', sa.Text(), nullable=True),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('interview_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['separation_id'], ['separation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_interviews_id'), 'exit_interviews', ['id'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('present_address', sa.Text(), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_mobile', sa.String(length=20), nullable=True),
    sa.Column('education_details', sa.Text(), nullable=True),
    sa.Column('experience_details', sa.Text(), nullable=True),
    sa.Column('uploaded_documents', sa.Text(), nullable=True),
    sa.Column('policy_acknowledgments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['onboarding_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_id'), 'form_submissions', ['id'], unique=False)
    op.create_table('offer_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('position_title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('basic_salary', sa.String(length=100), nullable=True),
    sa.Column('gross_salary', sa.String(length=100), nullable=True),
    sa.Column('ctc', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('offer_valid_until', sa.Date(), nullable=True),
    sa.Column('letter_content', sa.Text(), nullable=True),
    sa.Column('generated_file_path', sa.String(length=500), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['onboarding_forms.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['offer_letter_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_letters_id'), 'offer_letters', ['id'], unique=False)
    op.create_table('onboarding_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['onboarding_forms.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_documents_id'), 'onboarding_documents', ['id'], unique=False)
    op.create_table('onboarding_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('policy_content', sa.Text(), nullable=True),
    sa.Column('policy_file_path', sa.String(length=500), nullable=True),
    sa.Column('requires_acknowledgment', sa.Boolean(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['onboarding_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_policies_id'), 'onboarding_policies', ['id'], unique=False)
    op.create_table('separation_clearance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('separation_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'NOT_APPLICABLE', name='clearancestatus'), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('cleared_by', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('clearance_notes', sa.Text(), nullable=True),
    sa.Column('pending_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cleared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['separation_id'], ['separation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_separation_clearance_id'), 'separation_clearance', ['id'], unique=False)
    op.create_table('separation_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('separation_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['separation_id'], ['separation_requests.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_separation_documents_id'), 'separation_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_separation_documents_id'), table_name='separation_documents')
    op.drop_table('separation_documents')
    op.drop_index(op.f('ix_separation_clearance_id'), table_name='separation_clearance')
    op.drop_table('separation_clearance')
    op.drop_index(op.f('ix_onboarding_policies_id'), table_name='onboarding_policies')
    op.drop_table('onboarding_policies')
    op.drop_index(op.f('ix_onboarding_documents_id'), table_name='onboarding_documents')
    op.drop_table('onboarding_documents')
    op.drop_index(op.f('ix_offer_letters_id'), table_name='offer_letters')
    op.drop_table('offer_letters')
    op.drop_index(op.f('ix_form_submissions_id'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_exit_interviews_id'), table_name='exit_interviews')
    op.drop_table('exit_interviews')
    op.drop_index(op.f('ix_attendance_punches_id'), table_name='attendance_punches')
    op.drop_table('attendance_punches')
    op.drop_index(op.f('ix_attendance_corrections_id'), table_name='attendance_corrections')
    op.drop_table('attendance_corrections')
    op.drop_index(op.f('ix_shift_rosters_roster_date'), table_name='shift_rosters')
    op.drop_index(op.f('ix_shift_rosters_id'), table_name='shift_rosters')
    op.drop_table('shift_rosters')
    op.drop_index(op.f('ix_separation_requests_id'), table_name='separation_requests')
    op.drop_table('separation_requests')
    op.drop_index(op.f('ix_onboarding_forms_id'), table_name='onboarding_forms')
    op.drop_index(op.f('ix_onboarding_forms_form_token'), table_name='onboarding_forms')
    op.drop_index(op.f('ix_onboarding_forms_candidate_email'), table_name='onboarding_forms')
    op.drop_table('onboarding_forms')
    op.drop_index(op.f('ix_employee_salaries_id'), table_name='employee_salaries')
    op.drop_table('employee_salaries')
    op.drop_index(op.f('ix_employee_profiles_id'), table_name='employee_profiles')
    op.drop_table('employee_profiles')
    op.drop_index(op.f('ix_employee_documents_id'), table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_attendance_summaries_id'), table_name='attendance_summaries')
    op.drop_table('attendance_summaries')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_separation_templates_id'), table_name='separation_templates')
    op.drop_table('separation_templates')
    op.drop_index(op.f('ix_separation_settings_id'), table_name='separation_settings')
    op.drop_table('separation_settings')
    op.drop_index(op.f('ix_onboarding_settings_id'), table_name='onboarding_settings')
    op.drop_table('onboarding_settings')
    op.drop_index(op.f('ix_offer_letter_templates_id'), table_name='offer_letter_templates')
    op.drop_table('offer_letter_templates')
    op.drop_index(op.f('ix_bulk_onboarding_id'), table_name='bulk_onboarding')
    op.drop_table('bulk_onboarding')
    op.drop_index(op.f('ix_attendance_policies_id'), table_name='attendance_policies')
    op.drop_table('attendance_policies')
    # ### end Alembic commands ###
