"""Add CRM tables

Revision ID: d3e923ab9f67
Revises: ca4ba8b25a7a
Create Date: 2025-12-23 15:19:40.023673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e923ab9f67'
down_revision: Union[str, None] = 'ca4ba8b25a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attendance_corrections', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'attendance_policies', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'attendance_punches', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'attendance_records', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'attendance_records', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'bulk_onboarding', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'businesses', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'employee_documents', 'users', ['uploaded_by'], ['id'])
    op.create_foreign_key(None, 'employees', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'employees', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'offer_letter_templates', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'offer_letters', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'onboarding_documents', 'users', ['uploaded_by'], ['id'])
    op.create_foreign_key(None, 'onboarding_forms', 'users', ['rejected_by'], ['id'])
    op.create_foreign_key(None, 'onboarding_forms', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'onboarding_forms', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'onboarding_policies', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'onboarding_settings', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'shift_rosters', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift_rosters', type_='foreignkey')
    op.drop_constraint(None, 'onboarding_settings', type_='foreignkey')
    op.drop_constraint(None, 'onboarding_policies', type_='foreignkey')
    op.drop_constraint(None, 'onboarding_forms', type_='foreignkey')
    op.drop_constraint(None, 'onboarding_forms', type_='foreignkey')
    op.drop_constraint(None, 'onboarding_forms', type_='foreignkey')
    op.drop_constraint(None, 'onboarding_documents', type_='foreignkey')
    op.drop_constraint(None, 'offer_letters', type_='foreignkey')
    op.drop_constraint(None, 'offer_letter_templates', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employee_documents', type_='foreignkey')
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_constraint(None, 'bulk_onboarding', type_='foreignkey')
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_constraint(None, 'attendance_punches', type_='foreignkey')
    op.drop_constraint(None, 'attendance_policies', type_='foreignkey')
    op.drop_constraint(None, 'attendance_corrections', type_='foreignkey')
    # ### end Alembic commands ###
